### PR TITLE
Added Crowdfund page

### PR DESCRIPTION
**Pull request by krushiraj**
- Added page for crowdfund/[slug] dynamic path
- Added paths in /api/ for fetching data from airtable
- Modified PaymentForm to get it compatible with crowdfunding

### CODE REVIEW

**Comment by krushiraj** [comment]
@duttakapil don't we have a deploy preview feature when a PR is raised?

**Comment by vinaypuppal** [comment]
It's present but admins need to authorize PRs which have secrets like Razorpay credentials

**Comment by vinaypuppal** [comment]
The build failed, is it working locally for you?

**Comment by krushiraj** [comment]
I didn't build it locally. My node and npm installations were messed up yesterday. `next` command had issues. So I thought of raising a PR with WIP to see updates. When it didn't show up the preview link I thought previews will not be built for draft PRs so I made this ready for review.

**Comment by krushiraj** [comment]
I used `now dev` to see if they are working in dev version.

**Comment by krushiraj** [comment]
@vinaypuppal I have checked that `next build` works locally. Can you now authorize the preview deploy?

**Comment by vinaypuppal** [comment]
#### 📝Changed routes:


| [**/crowdfund**](https://donation-page-git-fork-krushiraj-crowdfund-feature.coderplex.now.sh/crowdfund) | [**/crowdfund/\[slug\]**](https://donation-page-git-fork-krushiraj-crowdfund-feature.coderplex.now.sh/crowdfund/[slug]) |
|:-:|:-:|
|<a href="https://donation-page-git-fork-krushiraj-crowdfund-feature.coderplex.now.sh/crowdfund">Screenshot of /crowdfund</a><br /><sup><a href="https://images.weserv.nl?url=microlink-screenshot.nyc3.digitaloceanspaces.com/E4zy7iqBdAcB6tufgFW1qIEXI6o_">(view full size)</a> |<a href="https://donation-page-git-fork-krushiraj-crowdfund-feature.coderplex.now.sh/crowdfund/[slug]">Screenshot of /crowdfund/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=microlink-screenshot.nyc3.digitaloceanspaces.com/WBPlY6eK_r5pJ43scBntiaz_0QA_">(view full size)</a> |



| [**/**](https://donation-page-git-fork-krushiraj-crowdfund-feature.coderplex.now.sh/) |
|:-:|
|<a href="https://donation-page-git-fork-krushiraj-crowdfund-feature.coderplex.now.sh/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=microlink-screenshot.nyc3.digitaloceanspaces.com/44St3NKgP_jGPaGoS7akAZN_JYs_">(view full size)</a> |



And 2 other routes:
- [**/api/campaigns**](https://donation-page-git-fork-krushiraj-crowdfund-feature.coderplex.now.sh/api/campaigns)
- [**/api/fundings**](https://donation-page-git-fork-krushiraj-crowdfund-feature.coderplex.now.sh/api/fundings)



Commit e06413e68edcbd503a3736830fee5c23b372cf19 (https://donation-page-git-fork-krushiraj-crowdfund-feature.coderplex.now.sh).

**Comment by vinaypuppal** [comment]
Done

**Comment by vinaypuppal** [comment]
Build were successful but both new routes you added show internal server error.

**Comment by krushiraj** [comment]
I have added 2 new variables in `.env` file. That might be the problem. Also, we need 2 more tables in our `AirTable` to get this up. Will look into it.

**Comment by duttakapil** [comment]
Ready to deploy?

**Comment by krushiraj** [comment]
@duttakapil yeah. I've also added the changes that you asked for in the title and fixed the mobile UI, added a link in donate.coderplex.org index page, we should also have one in coderplex.org too. This is ready to merge now.

**Pull request merged**
